from fastapi import APIRouter
from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime, timezone
import uuid
from founderlens_ai.utils.logger import logger

router = APIRouter()

class InsightModel(BaseModel):
    id: str = Field(..., description="Unique generated ID for the insight item")
    type: str = Field(..., description="Insight classification: risk, opportunity, trend, action")
    title: str = Field(..., description="Insight heading title")
    description: str = Field(..., description="Detail observation descriptive copy")
    confidence: int = Field(..., ge=0, le=100, description="Confidence rating between 0 and 100")
    impact: str = Field(..., description="Impact severity: high, medium, low")
    agent: str = Field(..., description="Boardroom agent that flagged this trend")
    timestamp: str = Field(..., description="ISO 8601 formatted timestamp of execution")
    tags: List[str] = Field(default=[], description="Metadata tags")

class InsightsListResponse(BaseModel):
    insights: List[InsightModel] = Field(..., description="List of generated insight models")
    total: int = Field(..., description="Total count of insights in response")
    analysis_id: str = Field(..., description="Associated analysis or session ID")

@router.get("", response_model=InsightsListResponse, summary="Get dynamic business insights and trends")
async def get_insights(analysis_id: Optional[str] = None):
    """Returns insights generated by the InsightAgent boardroom run."""
    session_id = (analysis_id or "GLOBAL").upper()
    
    logger.log_event("API_ROUTE", "TASK_START", "InsightsService", {
        "message": f"Fetching insights for session: {session_id}",
        "session_id": session_id
    })

    import os
    import json

    insights = []
    
    # Try to load the latest run's actual generated insights
    try:
        log_dir = os.getenv("LOG_DIR", "./logs")
        results_path = os.path.join(log_dir, "analysis_results.json")
        if os.path.exists(results_path):
            with open(results_path, "r") as f:
                logs = json.load(f)
            if logs:
                # Retrieve the latest execution logs (either baseline or boardroom run)
                latest_run = logs[-1]
                logged_insights = latest_run.get("insights", [])
                
                for item in logged_insights:
                    if isinstance(item, str):
                        # On-the-fly parsing for legacy/raw string entries
                        is_risk = any(word in item.lower() for word in ["churn", "risk", "decline", "pressure", "drop", "critical", "complaint"])
                        is_opp = any(word in item.lower() for word in ["opportunity", "pivot", "implement", "market", "launch", "pricing"])
                        insight_type = "risk" if is_risk else ("opportunity" if is_opp else "trend")
                        
                        words = item.split()
                        title = " ".join(words[:4]) + ("..." if len(words) > 4 else "")
                        if title.endswith(".") or title.endswith(","):
                            title = title[:-1]
                            
                        insights.append(InsightModel(
                            id=str(uuid.uuid4()),
                            type=insight_type,
                            title=title,
                            description=item,
                            confidence=90,
                            impact="high" if is_risk else "medium",
                            agent="DirectLLM",
                            timestamp=datetime.now(timezone.utc).isoformat(),
                            tags=["Baseline", insight_type.capitalize()]
                        ))
                    elif isinstance(item, dict):
                        # Clean dictionary load for modern structured entries
                        insights.append(InsightModel(
                            id=item.get("id", str(uuid.uuid4())),
                            type=item.get("type", "trend"),
                            title=item.get("title", "Insight Title"),
                            description=item.get("description", "No description provided."),
                            confidence=item.get("confidence", 90),
                            impact=item.get("impact", "medium"),
                            agent=item.get("agent", "DirectLLM"),
                            timestamp=item.get("timestamp", datetime.now(timezone.utc).isoformat()),
                            tags=item.get("tags", ["Live"])
                        ))
                
                # Expose action chain items as type="action" for the Android Action tab!
                action_chain = latest_run.get("action_chain", [])
                if isinstance(action_chain, list):
                    for action in action_chain:
                        if isinstance(action, dict):
                            insights.append(InsightModel(
                                id=str(uuid.uuid4()),
                                type="action",
                                title=action.get("title", action.get("action", "Proposed Action")),
                                description=action.get("description", action.get("result", "Strategic boardroom execution step.")),
                                confidence=95,
                                impact=action.get("priority", "medium").lower(),
                                agent="ActionPlanner",
                                timestamp=datetime.now(timezone.utc).isoformat(),
                                tags=["Courtroom", "Action"]
                            ))
                        elif isinstance(action, str):
                            insights.append(InsightModel(
                                id=str(uuid.uuid4()),
                                type="action",
                                title="Proposed Action",
                                description=action,
                                confidence=95,
                                impact="medium",
                                agent="ActionPlanner",
                                timestamp=datetime.now(timezone.utc).isoformat(),
                                tags=["Courtroom", "Action"]
                            ))
    except Exception as e:
        logger.log_event("API", "ERROR", "InsightsService", {"message": f"Failed to load latest logged insights: {str(e)}"})

    # No analysis has been run yet — return empty, no hardcoded data
    if not insights:
        logger.log_event("API_ROUTE", "INFO", "InsightsService", {
            "message": "No analysis results found. Run an analysis first to generate insights."
        })

    logger.log_event("API_ROUTE", "TASK_COMPLETE", "InsightsService", {
        "message": f"Successfully retrieved {len(insights)} insights for session: {session_id}",
        "session_id": session_id
    })

    return InsightsListResponse(
        insights=insights,
        total=len(insights),
        analysis_id=session_id
    )
