-- 🚀 FounderLens AI: Database Setup for Supabase
-- Run this script in your Supabase SQL Editor to initialize the required tables.

-- 1. Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Sessions Table
CREATE TABLE IF NOT EXISTS sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    startup_name TEXT,
    scenario TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Analysis Results Table
CREATE TABLE IF NOT EXISTS analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT, -- Using TEXT to match unified_package["session_id"] which might not be a UUID
    startup_name TEXT,
    insights JSONB,
    contradictions JSONB,
    action_chain JSONB,
    simulation_result JSONB,
    raw_result TEXT,
    total_runtime_seconds FLOAT,
    cost_estimate_usd FLOAT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Antigravity Trace Table (Live Logs)
CREATE TABLE IF NOT EXISTS antigravity_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    layer TEXT,
    type TEXT,
    agent TEXT,
    data JSONB
);

-- 5. Enable Realtime for live trace (Optional but recommended for mobile APK)
ALTER PUBLICATION supabase_realtime ADD TABLE antigravity_trace;
